"""
streamlit demo for the SOC Co-pilot agent.
run with: streamlit run src/app.py

week 15: the form used to collect "Title" and "Evidence", neither of which any
node reads -- build_context looks for "AlertTitle" -- so the two free-text
boxes a human actually typed into were silently dropped on the floor. Worse,
they were also the only inputs the schema guardrail did not inspect, since it
validates AlertTitle/DetectorId. The form now sends the field names the
pipeline really uses, so what you type is what gets triaged and what gets
guarded.
"""

import sys
import os

# streamlit doesn't add the repo root to the python path automatically,
# so we do it manually here — this lets "from src.agent..." imports work
# no matter which folder you launch streamlit from.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import streamlit as st
from src.agent.graph import triage_graph
from src.agent.nodes import RF_REVIEW_MARGIN_THRESHOLD

st.set_page_config(page_title="SOC Co-pilot", page_icon="🛡️", layout="centered")

st.title("🛡️ SOC Co-pilot")
st.caption(
    "Alert triage — a Random Forest assigns the verdict, an LLM explains it. "
    "Low-margin verdicts are held for human review."
)

st.subheader("alert fields")
st.caption(
    "GUIDE alert titles and detector ids are numeric codes, not prose — that is "
    "normal for this dataset. Non-numeric values are rejected by the schema guardrail."
)

col1, col2 = st.columns(2)
with col1:
    alert_title = st.text_input("AlertTitle", placeholder="e.g. 15723 (numeric GUIDE code)")
    detector_id = st.text_input("DetectorId", placeholder="e.g. 7 (numeric GUIDE code)")
    category = st.text_input("Category", placeholder="e.g. InitialAccess")
with col2:
    mitre_technique = st.text_input("MitreTechniques", placeholder="e.g. T1078;T1078.004")
    suspicion_level = st.text_input("SuspicionLevel", placeholder="e.g. Suspicious")
    last_verdict = st.text_input("LastVerdict", placeholder="e.g. NoThreatsFound")

if st.button("run triage", type="primary"):
    # Only send fields the analyst actually filled in. Empty strings would read
    # as present-but-blank and skew the evidence count that drives routing.
    raw_alert = {
        key: value
        for key, value in {
            "AlertTitle": alert_title,
            "DetectorId": detector_id,
            "Category": category,
            "MitreTechniques": mitre_technique,
            "SuspicionLevel": suspicion_level,
            "LastVerdict": last_verdict,
        }.items()
        if value and value.strip()
    }

    with st.spinner("running agent..."):
        result = triage_graph.invoke({"raw_alert": raw_alert})

    st.divider()
    st.subheader("result")

    verdict = result.get("predicted_label") or "no verdict"
    confidence = result.get("confidence", "unknown")
    needs_review = result.get("needs_human_review", False)
    margin = result.get("rf_margin")

    verdict_colors = {
        "TruePositive": "🔴",
        "BenignPositive": "🟡",
        "FalsePositive": "🟢",
    }
    icon = verdict_colors.get(verdict, "⚪")

    c1, c2, c3 = st.columns(3)
    c1.metric("verdict", f"{icon} {verdict}")
    c2.metric(
        "RF decision margin",
        f"{margin:.2f}" if margin is not None else "n/a",
        help=(
            "Top-1 minus top-2 class probability. Verdicts below "
            f"{RF_REVIEW_MARGIN_THRESHOLD:.2f} are held for human review."
        ),
    )
    c3.metric("human review needed", "yes" if needs_review else "no")

    rationale = result.get("rationale")
    if rationale:
        st.write("**analyst explanation** (generated by the LLM, which does not decide the verdict):")
        st.info(rationale)
    elif result.get("rationale_status") == "unavailable":
        st.warning(
            "The explanation model was unavailable, so this verdict is shown without a "
            "written rationale. The verdict itself is unaffected — it comes from the "
            "Random Forest, not the LLM."
        )

    st.write("**how this verdict was reached:**")
    st.write(result.get("reasoning", "n/a"))

    if result.get("mitre_context"):
        st.write("**MITRE ATT&CK context used:**")
        st.info(result["mitre_context"])

    if needs_review:
        st.warning(
            "Flagged for human review — see the reason above. Nothing here should be "
            "actioned automatically."
        )

    with st.expander("raw agent state"):
        st.json(result)
